###################################################
###          Install required packages          ###
###################################################
library(dplyr)
library(tidyr)
###################################################
###                 Import Data                 ###
###################################################
# NOTE: This script is a template that should be revised for each drug. This is written for LM: change LM to drug of interest for data import and in names of files generated by write.csv.

#setwd("") same wd as in IC50_assocations_step1.R

# Make new directory within working directory named "Wil_output" within working directory where output will be written.

rm(list=ls())
all_data <- read.csv("Wil_databases/MIP_LM_data.csv")

###################################################
###         Format file for filtering           ###
###################################################
names(all_data)[2] <- "drug"

# subset to include only isolates w/ drug sensitivity data
all_drug <- subset(all_data, !is.na(drug))
lng_drug <- length(all_drug)
all_drug_genotypes <- all_drug[3:lng_drug]

########################
# filter samples
########################
# count missing genotypes
all_drug$missing_persample <- apply(all_drug_genotypes, 1, function(x){sum(is.na(x))})
summary(all_drug$missing_persample)
data_filt_samples <- subset(all_drug, missing_persample < 5700, select = -c(missing_persample))

rm(all_drug, all_drug_genotypes)
########################
# filter loci
########################
filt_drug_genotypes <- data_filt_samples[3:lng_drug]

# select polymorphic loci (not just WT)
polymorphic_drug <- colSums(filt_drug_genotypes, na.rm = TRUE) > 0
table(polymorphic_drug)
variable_l <- filt_drug_genotypes[polymorphic_drug]

rm(filt_drug_genotypes, polymorphic_drug)

# select polymorphic loci (not just Mutant)
polymorphic_drug_mut <- sapply(variable_l, function(x) any(x != 2, na.rm=T))
table(polymorphic_drug_mut)
variable_ll <- variable_l[polymorphic_drug_mut]

polymorphic_drug_mix <- sapply(variable_ll, function(x) any(x != 1, na.rm=T))
table(polymorphic_drug_mix)
variable_lll <- variable_ll[polymorphic_drug_mix]

rm(polymorphic_drug_mut, variable_l, variable_ll)

# remove loci that are missing too much data
variable_lc <- variable_lll
#missing_perlocus <- sapply(variable_ll, function(x) sum(!is.na(x))) < length(variable_ll[,1])/2
#table(missing_perlocus)
#variable_lc <- variable_ll[!missing_perlocus]

drug <- subset(data_filt_samples, select= c(id, drug))
data_filt <- cbind(drug, variable_lc)

########################
# make subfiles for analysis
########################
data_long <- pivot_longer(data_filt, 3:length(names(data_filt)), names_to = "locus", values_to = "genotype")

tab <- as.data.frame(xtabs(~locus + genotype, data_long))
tab_wide <- spread(tab, genotype, Freq)
names(tab_wide) <- c("locus", "WT_N", "Mix_N", "Mut_N")
tab_wide$N <- tab_wide$WT_N + tab_wide$Mix_N + tab_wide$Mut_N
tab_wide$WT_f <- round(tab_wide$WT_N/tab_wide$N * 100, 1)
tab_wide$Mix_f <- round(tab_wide$Mix_N/tab_wide$N * 100, 1)
tab_wide$Mut_f <- round(tab_wide$Mut_N/tab_wide$N * 100, 1)
tab_wide$WT_Mix_f <- round((tab_wide$WT_N + tab_wide$Mix_N)/tab_wide$N * 100, 1)
tab_wide$Mix_Mut_f <- round((tab_wide$Mix_N + tab_wide$Mut_N)/tab_wide$N * 100, 1)

tab_wide <- subset(tab_wide, select = c("locus", "N", "WT_N", "Mix_N", "Mut_N", "WT_f", "Mix_f", "Mut_f",  "WT_Mix_f",  "Mix_Mut_f"))
rm(tab)

# higher or equal prevalence of WT compared to  Mut
tab_wide_standard <- subset(tab_wide, WT_Mix_f >= Mix_Mut_f)
loc_wide_standard <- tab_wide_standard$locus
standard_prev <- subset(data_long, locus %in% loc_wide_standard)
standard_prev$genotype_bi <- ifelse(standard_prev$genotype==2, 1, standard_prev$genotype)

standard_prev_cat <- subset(standard_prev, select = c(id, locus, genotype))
standard_wide <- pivot_wider(standard_prev_cat, names_from = locus, values_from = genotype)
standard_wide <- merge(drug, standard_wide, by = "id")

standard_prev_bi <- subset(standard_prev, select = c(id, locus, genotype_bi))
standard_wide_bi <- pivot_wider(standard_prev_bi, names_from = locus, values_from = genotype_bi)
standard_wide_bi <- merge(drug, standard_wide_bi, by = "id")

# higher prevalence of Mut than WT
tab_wide_swap_maj_min <- subset(tab_wide, WT_Mix_f < Mix_Mut_f)
loc_swap_maj_min <- tab_wide_swap_maj_min$locus
swap_prev <- subset(data_long, locus %in% loc_swap_maj_min)
swap_prev$genotype_bi <- ifelse(swap_prev$genotype==1, 0, swap_prev$genotype)

swap_prev_cat <- subset(swap_prev, select = c(id, locus, genotype))
swap_wide <- pivot_wider(swap_prev_cat, names_from = locus, values_from = genotype)
swap_wide <- merge(drug, swap_wide, by = "id")

swap_prev_bi <- subset(swap_prev, select = c(id, locus, genotype_bi))
swap_wide_bi <- pivot_wider(swap_prev_bi, names_from = locus, values_from = genotype_bi)
swap_wide_bi <- merge(drug, swap_wide_bi, by = "id")

########################################
# for wt as minority allele:
column_names <- data.frame(locus = "locus", 
                           N_samples = "N", 
                           N_wt = "N_wt", 
                           N_mixmut = "N_mixmut", 
                           medianwt = "median_wt", 
                           medianmixmut = "median_mixmut", 
                           tes = "p-value",
                           N_wt = "N_wt",
                           N_mix = "N_mix",
                           N_mut = "N_mut",
                           medianwt = "median_wt",
                           medianmix = "median_mix",
                           medianmut = "median_mut")
write.table(column_names, file = "Wil_output/LM_standard_output.csv", row.names = FALSE, append = FALSE, col.names = FALSE, sep = ",", quote = TRUE)

lng_std_wide_bi <- length(names(standard_wide_bi))
for(j in 3:lng_std_wide_bi){ #j = loci
  locus<-colnames(standard_wide_bi)[j]
  N_samples <- length(which((standard_wide_bi[,j]==0 | standard_wide_bi[,j]==1)))
  N_wt <- length(which((standard_wide_bi[,j]==0)))
  N_mixmut <- length(which((standard_wide_bi[,j]==1)))
  medianwt <- median(standard_wide_bi$drug[which(standard_wide_bi[j]==0)], na.rm=TRUE)
  medianmixmut <- median(standard_wide_bi$drug[which(standard_wide_bi[j]==1)], na.rm=TRUE)
  tes <- wilcox.test(standard_wide_bi$drug ~ standard_wide_bi[,j])$p.value
  N_wt <-  length(which((standard_wide[,j]==0)))
  N_mix <-  length(which((standard_wide[,j]==1)))
  N_mut <-  length(which((standard_wide[,j]==2)))
  medianwt <- median(standard_wide$drug[which(standard_wide[j]==0)], na.rm=TRUE)
  medianmix <- median(standard_wide$drug[which(standard_wide[j]==1)], na.rm=TRUE)
  medianmut <- median(standard_wide$drug[which(standard_wide[j]==2)], na.rm=TRUE)
  newline <- data.frame(t(c(locus, N_samples, N_wt, N_mixmut, medianwt, medianmixmut, tes, N_wt, N_mix, N_mut, medianwt, medianmix, medianmut)))
  write.table(newline, file="Wil_output/LM_standard_output.csv", row.names = FALSE, append = TRUE, col.names = FALSE, sep = ",")
}

########################################
column_names <- data.frame(locus = "locus", 
                           N_samples = "N", 
                           N_wtmix = "N_wtmix", 
                           N_mut = "N_mut", 
                           medianwtmix = "median_wtmix", 
                           medianmut = "median_mut", 
                           tes = "p-value",
                           N_wt = "N_wt",
                           N_mix = "N_mix",
                           N_mut = "N_mut",
                           medianwt = "median_wt",
                           medianmix = "median_mix",
                           medianmut = "median_mut")
write.table(column_names, file = "Wil_output/LM_swap_output.csv", row.names = FALSE, append = FALSE, col.names = FALSE, sep = ",", quote = TRUE)

lng_swap_wide_bi <- length(names(swap_wide_bi))
for(j in 3:lng_swap_wide_bi){ #j = loci
  locus<-colnames(swap_wide_bi)[j]
  N_samples <- length(which((swap_wide_bi[,j]==0 | swap_wide_bi[,j]==1)))
  N_wtmix <-   length(which((swap_wide_bi[,j]==0)))
  N_mut <- length(which((swap_wide_bi[,j]==1)))
  medianwtmix <- median(swap_wide_bi$drug[which(swap_wide_bi[j]==0)], na.rm=TRUE)
  medianmut <- median(swap_wide_bi$drug[which(swap_wide_bi[j]==1)], na.rm=TRUE)
  tes<-(wilcox.test(swap_wide_bi$drug ~ swap_wide_bi[,j])$p.value)
  N_wt <- length(which((swap_wide[,j]==0)))
  N_mix <- length(which((swap_wide[,j]==1)))
  N_mut <- length(which((swap_wide_bi[,j]==2)))
  medianwt <- median(swap_wide$drug[which(swap_wide[j]==0)], na.rm=TRUE)
  medianmix <- median(swap_wide$drug[which(swap_wide[j]==1)], na.rm=TRUE)
  medianmut <- median(swap_wide$drug[which(swap_wide[j]==2)], na.rm=TRUE)
  newline <- data.frame(t(c(locus, N_samples, N_wtmix, N_mut, medianwtmix, medianmut, tes, N_wt, N_mix, N_mut, medianwt, medianmix, medianmut)))
  write.table(newline, file="Wil_output/LM_swap_output.csv", row.names = FALSE, append = TRUE, col.names = FALSE, sep = ",")
}

quantile(standard_wide_bi$drug[which(standard_wide_bi$k13.Cys469Tyr == 0)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide_bi$k13.Cys469Tyr == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$k13.Cys469Tyr == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$k13.Cys469Tyr == 2)], na.rm= TRUE)

quantile(standard_wide_bi$drug[which(standard_wide_bi$k13.Ala675Val == 0)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide_bi$k13.Ala675Val == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$k13.Ala675Val == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$k13.Ala675Val == 2)], na.rm= TRUE)

quantile(standard_wide_bi$drug[which(standard_wide_bi$mdr1.Asn86Tyr == 0)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide_bi$mdr1.Asn86Tyr == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$mdr1.Asn86Tyr == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$mdr1.Asn86Tyr == 2)], na.rm= TRUE)

quantile(standard_wide_bi$drug[which(standard_wide_bi$mdr1.Tyr500Asn == 0)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide_bi$mdr1.Tyr500Asn == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$mdr1.Tyr500Asn == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$mdr1.Tyr500Asn == 2)], na.rm= TRUE)

quantile(standard_wide_bi$drug[which(standard_wide_bi$mdr1.Phe938Tyr == 0)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide_bi$mdr1.Phe938Tyr == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$mdr1.Phe938Tyr == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$mdr1.Phe938Tyr == 2)], na.rm= TRUE)

quantile(standard_wide_bi$drug[which(standard_wide_bi$mdr1.Phe938Tyr == 0)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide_bi$mdr1.Phe938Tyr == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$mdr1.Phe938Tyr == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$mdr1.Phe938Tyr == 2)], na.rm= TRUE)


quantile(standard_wide_bi$drug[which(standard_wide_bi$PF3D7.0218600.Ile1478Asn == 0)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide_bi$PF3D7.0218600.Ile1478Asn == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$PF3D7.0218600.Ile1478Asn == 1)], na.rm= TRUE)
quantile(standard_wide_bi$drug[which(standard_wide$PF3D7.0218600.Ile1478Asn == 2)], na.rm= TRUE)
